name: Develop Deployment
on:
  workflow_dispatch:

jobs:
  Deploy:
    env:
      AWS_S3_IMAGES: "internn-images-dev"
      AWS_S3_BUILD: "internn-frontend-dev"
      CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID_DEV }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1
        with:
          ref: "feature/re-design"
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Yarn Install
        run: |
          yarn install
      - name: Yarn Build
        run: |
          CI=false yarn predeploy
      - name: Unit Tests
        run: |
          yarn test
      - name: Deploy images to S3
        run: aws s3 sync --delete images/ s3://${AWS_S3_IMAGES}
      - name: Deploy build to S3
        run: aws s3 sync --delete build/ s3://${AWS_S3_BUILD}
      - name: Invalidate Cloudfront caches
        run: aws create-invalidation --distribution-id ${{ CLOUDFRONT_DISTRIBUTION_ID }} --paths '/*'
