name: Production S3 Sync
on:
  workflow_dispatch:

jobs:
  Sync:
    runs-on: ubuntu-latest
    env:
      AWS_S3_INFO: "internn-web-info-prod"
    steps:
      - uses: actions/checkout@v1
        with:
          ref: "master"
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
      - name: Format images
        shell: bash
        run: bash "./.github/scripts/resize_images.sh"
      - name: Sync s3 directory
        run: aws s3 sync --delete s3/ s3://${AWS_S3_INFO}
      - name: Invalidate Cloudfront caches
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID_PROD }} --paths '/*'
